name: Build and Run Go Program
on: [push]
jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        nodes: ["10.0.2.168", "10.0.2.167"]

    steps:
      - name: Deploy to ${{ matrix.nodes }}
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
        run: |
          # ssh-keyscan $SERVER_2_HOST >> ~/.ssh/known_hosts
          # echo "$SSH_PRIVATE_KEY" > ~/.ssh/github_actions
          # chmod 600 ~/.ssh/github_actions
          ssh -i ~/.ssh/github_actions $SSH_USERNAME@${{ matrix.nodes }} "docker run -d \
          -p 5000:5000 \
          --name web_app \
          -e REDIS_HOST="${redis_host}" \
          -e DB_HOST="${db_host}" \
          -e DB_USER="user" \
          -e DB_PASSWORD="password" \
          -e DB_NAME="mydatabase" \
          sarakalhussain/devops:latest"