name: Build & Test

on: [push, pull_request]

jobs:
  Unit-Tests:
    runs-on: ubuntu-latest 
    steps:
    # for PR & Push
      - name: Checkout
        uses: actions/checkout@v3

      - name: Running Unit Tests
        run: |
          docker compose run test 

  Docker-Build:
    runs-on: ubuntu-latest 
    needs: Unit-Tests  
    if: github.event_name == 'push'  

    steps:
      - name: Docker Setup
        uses: docker/setup-buildx-action@v3

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Build & push
        uses: docker/build-push-action@v6
        with: 
          push: true
          tags: |
            dunaalsulaiman/capstone-project:latest
            dunaalsulaiman/capstone-project:${{ github.run_number }}
            dunaalsulaiman/capstone-project:${{ github.sha }}
          # cache-from: dunaalsulaiman/capstone-project:latest
          # cache-to: type-inline